// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import ButtonController from "./button_controller"
application.register("button", ButtonController)

import CompareController from "./compare_controller"
application.register("compare", CompareController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import SwipeController from "./swipe_controller"
application.register("swipe", SwipeController)

import RestoreValuesController from "./restore_values_controller"
application.register("restore-values", RestoreValuesController)

//  ローディングアニメーション読み込み
import LoadingController from "./loading_controller"
application.register("loading", LoadingController)
