# Rubyのバージョン指定
FROM ruby:3.4.8

# 文字コードをUTF-8に設定（日本語を正しく扱うため）
ENV LANG C.UTF-8

# 時刻を日本時間（Asia/Tokyo)に設定
ENV TZ Asia/Tokyo

# Linuxのアプリストアを最新の状態に更新
# Linuxのアプリストアからca-certificates curl gnupgの3つのソフトウェアをインストール
# /etc/apt/keyringsディレクトリの作成
# Node.jsの公式サイトから暗号鍵をダウンロードして、/etc/apt/keyrings/nodesource.gpgに保存
# 20という値をNODE_MAJORに保存
# Node.jsのリポジトリ情報をLinuxのパッケージリストに追加
RUN apt-get update -qq \
&& apt-get install -y ca-certificates curl gnupg \
&& mkdir -p /etc/apt/keyrings \
&& curl -fsSL https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key | gpg --dearmor -o /etc/apt/keyrings/nodesource.gpg \
&& NODE_MAJOR=20 \
&& echo "deb [signed-by=/etc/apt/keyrings/nodesource.gpg] https://deb.nodesource.com/node_$NODE_MAJOR.x nodistro main" | tee /etc/apt/sources.list.d/nodesource.list

# apt-key addは非推奨のため以下2行は使用しない。
#&& wget --quiet -O - /tmp/pubkey.gpg https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add - \
#&& echo "deb https://dl.yarnpkg.com/debian/ stable main" | tee /etc/apt/sources.list.d/yarn.list

# Yarnのリポジトリ設定（改善版）
RUN curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | gpg --dearmor -o /usr/share/keyrings/yarn-archive-keyring.gpg \
&& echo "deb [signed-by=/usr/share/keyrings/yarn-archive-keyring.gpg] https://dl.yarnpkg.com/debian/ stable main" | tee /etc/apt/sources.list.d/yarn.list
# Linuxのアプリストアを最新の状態に更新して、Railsアプリに必要な道具をインストールする
RUN apt-get update -qq && apt-get install -y build-essential libpq-dev nodejs yarn vim
# /myappディレクトリの作成
RUN mkdir /myapp
# 以降は/myappディレクトリ内で作業
WORKDIR /myapp
# Bundler（バンドラー）gemをインストール
RUN gem install bundler
# 現在のディレクトリにある全てをDockerコンテナの/myappディレクトリにコピー
COPY . /myapp